[[GIAC]]
arch = "aarch64"
git-tree-sha1 = "ecf2beae5145924fc8d151fa5b57b85738c8367b"
os = "macos"

    [[GIAC.download]]
    sha256 = "45ad448bcab5d8af5805d56c62004effdbfc96decd0824235ededa85c7e2945c"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.aarch64-apple-darwin.tar.gz"
[[GIAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37a5c3cf4869ea11dc86037fec007f768776b0ea"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "c1ea2af6c7c4b8ee8a38462069a5f94ed64c4830cbdcf18ec25ac3cd042c0780"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c324e6680dce06ffaac21d8385b7142f7dcad73"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "451fb5fed31fc416309c14ff5e17dcfece5e3d1f8e3afc1cad7fbe6ede239b87"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "aarch64"
git-tree-sha1 = "5840606fd6741d6fe48dad4dae93a5261c7ae591"
os = "freebsd"

    [[GIAC.download]]
    sha256 = "e92e73d900e31b01b66240a4e6314240ae7e9545671a6e2053bc4da640712794"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.aarch64-unknown-freebsd.tar.gz"
[[GIAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eea742ed668578218ca8a355460ed1be1d54b3f0"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "ef56f674296b9bfed824d273335076f2a6516745248f7c5d1b45cafc5aa56fcf"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ad3a9480f50a5854145a15dca72415f4d61fb76"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "56b3f5e48c1f47e8ffadb57f7ea223b7beb683095f8c448b618f62623af9f28b"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19a36e0c47199921d9ced764e0d14d1c3cfc5fd7"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "ac6f6108eb138e63d802012423370fb52d3602feefd66dee586616af3bee4cbe"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cb23ad491b5ee51de87af30220648e4094dddcb"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "5f1d422258334c28dc3e4feaa4a54156513a8a82851030448723f1ff26af61e4"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d300a9f560372c27cb50a364817bae1461a559ef"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "bf70329eacf81a038809c9c86ee4c5ef39bf755ff049e2d900691774cf7da262"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.i686-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db749af26857449617e67854c87de143e3048177"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "03712ac8231c495988f6f891224ca22d23c473cd360521078c4ccb78d8164a74"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.i686-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30354097847af2321e0490a4910387c8610f05a7"
os = "windows"

    [[GIAC.download]]
    sha256 = "118fb8bfd6f941f5da1e768d39a609822bc1bcc914ea6b5b3a50d6de28140abd"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[GIAC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8593108d6e11d074462dc81a3c880a5978de4f46"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "5bda4780156b405919ac7178c42fc84dc7f59b5a3f97696f7d04347dae131eee"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c5ff6d010207986d0a5727a113c9d28400b2dc7"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "69aa86c0ee26fca5d6e9c20e468ea64c68e927004172a91dfb94e7b6b853024d"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.riscv64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
git-tree-sha1 = "52efac1c3dff853948958872a3a457c7185077b6"
os = "macos"

    [[GIAC.download]]
    sha256 = "845f28e2217d96f21ca7ef217905a3cc225bb32dec2048b01e5b86c8aaf8e21b"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.x86_64-apple-darwin.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6d5f8cc3e0b0c26b7db5c476fac3ad102a7bfd3"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "8c0169dbac0bd52c35cfe3dbea1745d2fda1c2d6a034b490f1e640b9fccfdcba"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbbb0731cf428836928a7c29c6267b5cbfe300e1"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "72a6033a98352fccbb0ac5f0e4e3e887d3d589fc083c5c71a049e1d5b365a27b"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
git-tree-sha1 = "8c0cae0bf76aae65755efb7dfb54a553ccc5422c"
os = "freebsd"

    [[GIAC.download]]
    sha256 = "ef2569df4e5c437f9b16fc3db9a8ca2e49dc5d6ddce991c6297a470c15333028"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.x86_64-unknown-freebsd.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e04994d5cee076f5794487a2e248e1faf70da8f"
os = "windows"

    [[GIAC.download]]
    sha256 = "885ab2cd164d8e78b5b9004a3b0223fbfdd70e32f6344c9a63e1368ade232b68"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.1+0/GIAC.v2.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
