[[GIAC]]
arch = "aarch64"
git-tree-sha1 = "5e8a831d0fef5a74fbcadfe357b7a932313b9fe1"
os = "macos"

    [[GIAC.download]]
    sha256 = "605fda9bb8d5b0eb129ae66c782f2a0d41f4f623f6843fab6e85e4995bd129f0"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.aarch64-apple-darwin.tar.gz"
[[GIAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36742c8cf5e44266ec3a4466318bdb3b9e0e71ed"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "607394bd95dea9077a3ff44dc6879b2d609f514401aaf8b390030c3c04f9b978"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4559a7e1f334e133809904e08ef499e2232f08a8"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "8a74c4e0d48d5b4a385c06e7fb8c8f8d31e2153fcaf0944362412c473885b2bc"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "aarch64"
git-tree-sha1 = "674e8674fcddd3f3438e68715f70f0232b1d496f"
os = "freebsd"

    [[GIAC.download]]
    sha256 = "633ed4cbe8c2c05e2faed5b4f43fce2aaf376b68f2a59ac1c97c840585220411"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.aarch64-unknown-freebsd.tar.gz"
[[GIAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01d315a15248553082417eda245cfd0dba625b23"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "32bc922ac1fecfa9cfddc479d435280789e55f391031761e3297fa5d178b16e3"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c37ab3ca58f46caa38e8f69cdfefe90dbf37b9a0"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "b0ebba2b3f651b4913832517acacd79658601c6df2607450254af821f68b94c8"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9ae5514d27b942ef18228bec1af33ab9bb547a9"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "102a4caf04a4958a6ab609a6589b0259800151b8052b47adb545ce64cf133d83"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GIAC]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "577cb57355a02a501415b2f5864c334d778f0694"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "9728cb25c874ab6b904dbc837a45ea1116a406541536f648a89629fe4cbd78b9"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4005a81098f7a35716ae2902dee6c2cad7c883b4"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "379871c2c006bf3358f59a8d0fbc7f6bbedcbcb5dd6b5676db30cd93f32fa410"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.i686-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9da51e5368992f1a4d36e9d186891e45020cb7e8"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "b57edaace4df57a568af40d2ac8744f69d29157b3cf3a50e4e077b60068578a4"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.i686-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f472d5146e56a3cfae45590d947ee8fa4cfdcb4"
os = "windows"

    [[GIAC.download]]
    sha256 = "65d49726cda465043472f7c45c424401440508ebc4a3cf6c161c6bd11a57e024"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[GIAC]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "087f0dd6e8cd3d9d1e216934099f1d10453a50ea"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "814a505d4242cb3183b7d6c098ad28c172aabbaa7e4cdf30dd1a0ab190e74924"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d4f7eb2a921ae9b5aba215e764badd3551ac94d"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "681406bebb32aeb1c33728d6a773d9431b7d402882d065678ce5cb6d8954e991"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
git-tree-sha1 = "09a6cfc1b417fd0e8db09f415ef77db118a67f64"
os = "macos"

    [[GIAC.download]]
    sha256 = "8dd6b892a66d679cf96a45262bcdbf02ab511ef333d68d942be187607f32180e"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.x86_64-apple-darwin.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d278a3fc5d59c32863553fa32f7dd7691045cad7"
libc = "glibc"
os = "linux"

    [[GIAC.download]]
    sha256 = "d06d2b488ea5dfadd581eb8fc7bf5f569813a33c0ce18dda9654d97614716772"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07ffe8a04342731254c0f872b6372e0d2aef2ff4"
libc = "musl"
os = "linux"

    [[GIAC.download]]
    sha256 = "6ddcf4b7c3936e34001851925677172e600d8131b23fc831dc269a8d9459c2e3"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[GIAC]]
arch = "x86_64"
git-tree-sha1 = "6b16f703ff3e2ebaa7e2a5a838c18ca5bcb8a59c"
os = "freebsd"

    [[GIAC.download]]
    sha256 = "1c98cc5bde7536a51f833d3d8c00e4082d5af207f930c80971a650d780180565"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.x86_64-unknown-freebsd.tar.gz"
[[GIAC]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a3d1fcbd8fcd5487bf9639b9d2ad041e2fb3876"
os = "windows"

    [[GIAC.download]]
    sha256 = "06150c240bd38e6b4b12d472be5be37a528a60147a759c6266cad7d4f54e2337"
    url = "https://github.com/JuliaBinaryWrappers/GIAC_jll.jl/releases/download/GIAC-v2.0.0+0/GIAC.v2.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
