# Autogenerated wrapper script for GIAC_jll for aarch64-apple-darwin
export aide_cas, icas, libgiac

using Gettext_jll
using GMP_jll
using MPFR_jll
using Readline_jll
JLLWrappers.@generate_wrapper_header("GIAC")
JLLWrappers.@declare_file_product(aide_cas)
JLLWrappers.@declare_library_product(libgiac, "@rpath/libgiac.0.dylib")
JLLWrappers.@declare_executable_product(icas)
function __init__()
    JLLWrappers.@generate_init_header(Gettext_jll, GMP_jll, MPFR_jll, Readline_jll)
    JLLWrappers.@init_file_product(
        aide_cas,
        "share/giac/aide_cas",
    )

    JLLWrappers.@init_library_product(
        libgiac,
        "lib/libgiac.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        icas,
        "bin/icas",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
