# Autogenerated wrapper script for GIAC_jll for i686-linux-gnu-cxx11
export aide_cas, icas, libgiac

using Gettext_jll
using GMP_jll
using MPFR_jll
using Readline_jll
using GSL_jll
using OpenBLAS32_jll
using CompilerSupportLibraries_jll
using GLPK_jll
using PARI_jll
JLLWrappers.@generate_wrapper_header("GIAC")
JLLWrappers.@declare_file_product(aide_cas)
JLLWrappers.@declare_library_product(libgiac, "libgiac.so.0")
JLLWrappers.@declare_executable_product(icas)
function __init__()
    JLLWrappers.@generate_init_header(Gettext_jll, GMP_jll, MPFR_jll, Readline_jll, GSL_jll, OpenBLAS32_jll, CompilerSupportLibraries_jll, GLPK_jll, PARI_jll)
    JLLWrappers.@init_file_product(
        aide_cas,
        "share/giac/aide_cas",
    )

    JLLWrappers.@init_library_product(
        libgiac,
        "lib/libgiac.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        icas,
        "bin/icas",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
