# Autogenerated wrapper script for GIAC_jll for x86_64-w64-mingw32-cxx11
export aide_cas, libgiac

using GettextRuntime_jll
using GMP_jll
using MPFR_jll
JLLWrappers.@generate_wrapper_header("GIAC")
JLLWrappers.@declare_file_product(aide_cas)
JLLWrappers.@declare_library_product(libgiac, "libgiac-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(GettextRuntime_jll, GMP_jll, MPFR_jll)
    JLLWrappers.@init_file_product(
        aide_cas,
        "share\\giac\\aide_cas",
    )

    JLLWrappers.@init_library_product(
        libgiac,
        "bin\\libgiac-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
